# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.3"
darklua = "seaofvoices/darklua@0.13.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
selene = "kampfkarren/selene@0.27.1"
stylua = "johnnymorganz/stylua@0.20.0"
luau-lsp = "johnnymorganz/luau-lsp@1.32.4"
